### ISSUE TITLE
?

### ISSUE THREAD

**Issue by Boryyy** [Hybrid1337/Infinity-Bot#1]
what is this ? is this normal ?
![image](https://user-images.githubusercontent.com/60760570/112912029-e4358780-90f6-11eb-94b8-af0e965de873.png)

**Comment by Hybrid1337** [comment]
No its not normal, did you try installing all the libraries ?

**Comment by Boryyy** [comment]
oh thanks for ur time , yes i tried in windows , then linux shell does the same thing

**Comment by Hybrid1337** [comment]
Try using the newest version of python

**Comment by Boryyy** [comment]
i tried everthing idk :| , when it ask target id , i have to put username or id? i tried them both and still

**Comment by Hybrid1337** [comment]
the id

**Comment by Hybrid1337** [comment]
<img width="958" alt="Capture" src="https://user-images.githubusercontent.com/80607377/112915581-3d0d1c00-9107-11eb-909a-2d177e002c6b.PNG">
You basically inspect and then go to networking and then refresh the victoms page, and then search for ?no_raven=1 and then go to Response you will find the user_id

**Comment by Boryyy** [comment]
just tried it again still doesnt work , can u try it uraelf is it worling ?

**Comment by Boryyy** [comment]
maybe its nof dhe ID the problem , maybe proxies are bad? can i do this proxyless or upload mine?

**Comment by Boryyy** [comment]
![image](https://user-images.githubusercontent.com/60760570/112919764-01bf1d00-9108-11eb-9e1f-b279577598ab.png)
it shows this now

**Comment by Hybrid1337** [comment]
it already build in proxy, try pip install proxyscrape, pip install requests if it didn't work delete proxyscrape from the script plus its only for windows users.

**Comment by Boryyy** [comment]
the program cant run if the modules are not installed , i cant fix it i tried everything , thanks for ur time anyway

**Comment by Boryyy** [comment]
![image](https://user-images.githubusercontent.com/60760570/113215864-ce050400-927b-11eb-8979-9d55d5cae6e9.png)
